/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import finchssh.ProgControl;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Peabody
 */
public class RunPanel extends javax.swing.JPanel {

    File selectedFile;
    String filePath = "Select a File";
    ProgControl app;
    boolean fileReady = false;

    public RunPanel(ProgControl app) {
        this.app = app;
        initComponents();
        text_FileID.setText(filePath);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FileSelector = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        text_FileID = new javax.swing.JTextField();
        btn_GetFile = new javax.swing.JButton();
        btn_Run = new javax.swing.JButton();
        btn_Exit = new javax.swing.JButton();
        btn_Back = new javax.swing.JButton();

        FileSelector.setCurrentDirectory(new java.io.File("C:\\Users\\CJ\\Documents\\NetBeansProjects\\GitRepos\\FinchSSH\\FinchSSH"));
        FileSelector.setDialogTitle("");

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("File:");

        text_FileID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        text_FileID.setText("jTextField1");

        btn_GetFile.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_GetFile.setText("Get File");
        btn_GetFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GetFileActionPerformed(evt);
            }
        });

        btn_Run.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Run.setText("Run");
        btn_Run.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RunActionPerformed(evt);
            }
        });

        btn_Exit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Exit.setText("Exit");
        btn_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExitActionPerformed(evt);
            }
        });

        btn_Back.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Back.setText("Back");
        btn_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(text_FileID, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_GetFile)
                    .addComponent(btn_Run))
                .addContainerGap(66, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Exit)
                .addGap(71, 71, 71))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(text_FileID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_GetFile)
                .addGap(28, 28, 28)
                .addComponent(btn_Run)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Back)
                    .addComponent(btn_Exit))
                .addContainerGap(34, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExitActionPerformed
        System.out.println("Exit from RunWindow");
        System.exit(0);
    }//GEN-LAST:event_btn_ExitActionPerformed

    private void btn_GetFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GetFileActionPerformed
        // launch file selector,get path from selector, Assign path to filePath, update text_FileID
        int returnVal = FileSelector.showOpenDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            selectedFile = FileSelector.getSelectedFile();
            filePath = selectedFile.getPath();
            text_FileID.setText(selectedFile.getName());
            fileReady = true;
        } else {
            selectedFile = null;
            filePath = "Select a file";
            text_FileID.setText(filePath);
            fileReady = false;
            System.out.println("File Select canceled");
        }

    }//GEN-LAST:event_btn_GetFileActionPerformed

    private void btn_RunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RunActionPerformed
        if (fileReady) {
            app.doFinchRun(filePath, selectedFile.getName());
        } else {
            JOptionPane.showMessageDialog(this, "Select a File to continue");
        }

    }//GEN-LAST:event_btn_RunActionPerformed

    private void btn_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BackActionPerformed
        app.goToPropPanel();
    }//GEN-LAST:event_btn_BackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser FileSelector;
    private javax.swing.JButton btn_Back;
    private javax.swing.JButton btn_Exit;
    private javax.swing.JButton btn_GetFile;
    private javax.swing.JButton btn_Run;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField text_FileID;
    // End of variables declaration//GEN-END:variables
}
